const gBuildings = {
	"Hangar Bay": {
		name: "Hangar Bay",
		faction: 'v',
		subfaction: ['1v1', 'Blockade', 'Amara'],
		size: '4x4',
		luminite: 150,
		therium: 75,
		buildtime: 45,
		building_requirement: ['Central Command'],
		health: 1000,
		armor_type: ['Heavy', 'Mechanical', 'Structure'],
		armor:15,
	},
	"Mech Bay": {
		name: "Mech Bay",
		faction: 'v',
		subfaction: ['1v1', 'Blockade', 'Amara'],
		size: '4x4',
		luminite: 150,
		therium: 50,
		buildtime: 45,
		building_requirement: ['Barracks'],
		health: 1200,
		armor_type: ['Heavy', 'Mechanical', 'Structure'],
		armor: 15,
	},
	"Barracks": {
		name: "Barracks",
		faction: 'v',
		subfaction: ['1v1', 'Blockade', 'Amara'],
		size: '4x4',
		luminite:150,
		buildtime:40,
		health: 1200,
		building_requirement: ['Command Post'],
		armor_type: ['Heavy', 'Mechanical', 'Structure'],
		armor:15,
	},
	"Biokinetics Lab": {
		name: "Biokinetics Lab",
		faction: 'v',
		subfaction: ['1v1', 'Blockade', 'Amara'],
		size: '4x4',
		luminite: 100,
		buildtime: 50,
		building_requirement: ['Barracks'],
		health: 800,
		armor_type: ['Heavy', 'Mechanical', 'Structure'],
		armor:15,
	},
	"Machine Lab": {
		name: "Machine Lab",
		faction: 'v',
		subfaction: ['1v1', 'Blockade', 'Amara'],
		size: '4x4',
		luminite: 100,
		therium: 50,
		buildtime: 50,
		building_requirement: ['Central Command'],
		health: 800,
		armor_type: ['Heavy', 'Mechanical', 'Structure'],
		armor:15,
	},
	"Command Post": {
		name: "Command Post",
		faction: "v",
		subfaction: ["1v1", "Blockade", "Amara"],
		size: "6x6",
		luminite: 400,
		buildtime: 90,
		builds: "BOB",
		supply_gained: 15,
		upgrades_to: ["Central Command"],
		health: 1500,
		armor_type: ['Heavy', 'Mechanical', 'Structure'],
		armor:15,
	},
};