const gUnits = {
	"Argent": {
		displayName: "Argent",
		built: ["Creation Chamber"],
		faction: "c",
		type: "Ground",
		luminite: 100,
		therium: 0,
		supply: 2,
		buildtime: 26,
		speed: 4.5,
		size: 1.29,
		health: 180,
		armor_type: ['Biological', 'Heavy', 'Mechanical'],
		armor: 5,
		energy: 30,
		attacks: [{
			name: 'Oscillamata',
			target: ['Air', 'Ground'],
			damage: 8,
			speed: 1.5,
			bonus: [ { bonus: 'Heavy', bonus_damage: 4 }],
			range: 6,
		}],
		abilities: [{
			name: 'High Energy',
			energy: 10,
			desc: "Imbues this unit's weapon, allowing it to deal 100% increased damage. Right-click to enable/disable autocasting.",
		}],
		traits: [{
			name: 'Photo-Restoration',
			desc: "When this unit is out of combat, it regenerates 2 energy per second.",
		}, {
			name: 'Longshot Module',
			req: ['Research Photo-Capacitors', 'Research Longshot Module'],
			desc: "Increases the range of this unit's charged weapon by +3.",
		}, {
			name: 'Photo-Capacitors',
			req: ['Research Photo-Capacitors'],
			desc: "+20 starting and maximum energy.",
		}],
	},
	"Gaunt": {
		displayName: "Gaunt",
		built: ["Conclave"],
		faction: "i",
		type: "Ground",
		luminite: 50,
		therium: 12.5,
		supply: 1,
		buildtime: 0.5,
		charge_time: 35,
		speed: 4,
		size: 1.33,
		health: 80,
		extra_health: 20,
		armor_type: ['Biological', 'Light'],
		armor: 0,
		energy: 0,
		attacks: [{
			name: 'Flying Bone Axes',
			target: ['Air'],
			damage: 8,
			speed: 1.3,
			bonus: [ { bonus: 'Light', bonus_damage: 4 }],
			range: 6,
		}, {
			name: 'Bone Axes',
			target: ['Ground'],
			damage: 8,
			speed: 1.3,
			bonus: [ { bonus: 'Light', bonus_damage: 4 }],
			range: 5,
		}],
		extra_info: [{
			name: 'Spawns in pair',
			desc: "Charge makes 2 gaunts",
		}, {
			name: 'Bounces',
			desc: "Attacks bounce to two nearby targets, dealing 2 (+1 vs Light) damage.",
		}],
		abilities: [],
		traits: [{
			name: "Bouncing Bone Axes",
			range: 3.5,
			desc: "On-Hit: Attacks bounce twice to nearby enemies, dealing 25% of primary damage.",
		}, {
			name: 'Plague Axe',
			req: ['Research Plague Axe'],
			desc: "On-Hit: Attacked units within Shroud are infected with Infest.",
		}, {
			name: "Reaper's Rush",
			req: ["Research Reaper's Rush"],
			desc: "30% increased movement speed.",
		}],
	},
	"Atlas": {
		displayName: 'Atlas',
		built: ['Mech Bay'],
		faction: 'v',
		subfaction: ['1v1', 'Blockade', 'Amara'],
		type: 'Ground',
		building_requirement: ['Machine Lab'],
		luminite: 250,
		therium: 125,
		supply: 6,
		buildtime:48,
		speed:3,
		size: 2.75,
		health:300,
		armor_type: ['Heavy', 'Mechanical'],
		armor:10,
		veterancybonushealth: [60, 60, 60],
		veterancybonusdamage: ['10%', '10%', '10%'],
		veterancyspecialbonus: ['1 (Deployed) Range', '1 (Deployed) Range', '1 (Deployed) Range'],
		veterancyxp: [1200, 3000, 5400],
		attacks: [{
			name: 'L.I.G.H.T. Guns',
			target: ['Ground'],
			damage: 15,
			speed: 0.5,
			range: 4,
		}, {
			name: 'BFG',
			target: ['Ground'],
			damage: 80,
			speed: 5,
			bonus: [ { bonus: 'Heavy', bonus_damage: 35 }, { bonus: 'Structure', bonus_damage: 35 }],
			range: 16,
			minimumRange: 5,
		}],
		abilities: [{
			name: 'Deploy BFG',
			cooldown: 1.5,
			desc: "Deploy: Greatly increases the range of the Atlas' attack. Attacks Ground",
		}, {
			name: 'Pack It Up',
			cooldown: 1.167,
			desc: "Mobilize: Greatly reduce the range of the Atlas' attack. Attacks Ground",
		}],
		traits: [{
			name: 'Purification Ordnance',
			req: ['Deploy BFG'],
			desc: "This unit's attacks deal area damage in a circle.",
		}, {
			name: 'Plasma Arc Infusion',
			duration: 5,
			req: ['Research Plasma Arc Infusion'],
			desc: "On-Hit: Lights the ground on fire, dealing 20 damage per second to all units standing in the fire for 5 seconds.",
		}],
	},
	"BOB": {
		displayName: 'B.O.B.',
		built: ['Command Post', 'Central Command', 'High Command'],
		faction: 'v',
		subfaction: ['1v1', 'Blockade', 'Amara'],
		type: 'Ground',
		luminite: 50,
		therium: 0,
		supply: 1,
		buildtime: 17,
		speed: 3.5,
		size: 1,
		health: 130,
		armor_type: ['Light', 'Mechanical'],
		armor: 0,
		veterancybonushealth: [26, 26, 26],
		veterancybonusdamage: ['10%', '10%', '10%'],
		veterancyspecialbonus: ['20% Construction Speed', '20% Construction Speed', '20% Construction Speed'],
		veterancyxp: [200, 500, 900],
		attacks: [{
			name: 'Servo-Fists',
			target: ['Ground'],
			damage: 8,
			speed: 1.5,
			range: 0.1,
		}],
		abilities: [{
			name: 'Repair',
			desc: "Restores health to mechanical units and structures.",
		}],
	},
	"Lancer": {
		displayName: 'Lancer',
		built: ['Barracks'],
		faction: 'v',
		subfaction: ['1v1'],
		type: 'Ground',
		luminite: 100,
		therium: 0,
		supply: 2,
		buildtime: 24,
		speed: 4.5,
		size: 1.33,
		health: 260,
		armor_type: ['Biological', 'Heavy'],
		armor: 15,
		veterancybonushealth: [48, 48, 48],
		veterancybonusdamage: ['10%', '10%', '10%'],
		veterancyspecialbonus: ['5 Armor', '5 Armor', '5 Armor'],
		veterancyxp: [400, 1000, 1800],
		attacks: [{
			name: 'Foe Splitter Blade',
			target: ['Ground'],
			damage: 10,
			speed: 1.5,
			bonus: [ {bonus: 'Structure', bonus_damage:5 }, {bonus: 'Light', bonus_damage:5 }],
			range: 1.5,
		}],
		traits: [{
			name: 'Vanguard Fortified Impaler',
			desc: "This units attacks deal area damage in a line.",
		},{
			name: 'Vanguard Kinetic Redirection',
			duration: 5,
			req: ['Research Kinetic Redirection'],
			desc: "On-Damaged: Increases this unit's attack and movement speed by 5% for 5 seconds. Max 50%.",
		},{
			name: 'Vanguard Mitigative Guard',
			req: ['Research Mitigative Guard'],
			desc: "On-Damaged: Damage reduced by 2.",
		}],
	},
	"SCOUT": {
		displayName: "S.C.O.U.T.",
		built: ["Barracks"],
		faction: "v",
		subfaction: ["1v1", "Amara"],
		type: "Ground",
		luminite: 50,
		therium: 0,
		supply: 1,
		buildtime: 18,
		speed: 7,
		size: 1.33,
		health: 120,
		armor_type: ["Biological", "Light", "Mechanical"],
		armor: 0,
		veterancybonushealth: [24, 24, 24],
		veterancybonusdamage: ["10%", "10%", "10%"],
		veterancyspecialbonus: ["2 Vision", "2 Vision", "2 Vision"],
		veterancyxp: [200, 400, 900],
		attacks: [{
			name: "Metallic Cruncher",
			target: ["Ground"],
			damage: 5,
			speed: 1.4,
			bonus: [ {bonus: 'Light', bonus_damage: 3 }],
			range: 0.1
		}],
		abilities: [{
			name: "On The Hunt",
			cooldown: 40,
			duration: 10,
			desc: "Greatly increases the S.C.O.U.T.'s vision radius for 10 seconds."
		},{
			name: "Pounce",
			cooldown: 30,
			req: ["Research Pounce"],
			desc: "Intercepts a nearby enemy unit, increasing this unit's movement speed by 25% and dealing 15 (+15 vs Light) bonus damage on impact."
		}],
		traits: [{
			name: "Pupper Sense",
			desc: "This unit can sense nearby enemies under the fog of war."
		},{
			name: "Vorillium Claws",
			req: ["Research Vorillium Claws"],
			desc: "Increased damage against Light units by +8."
		},{
			name: "Detector",
			desc: "Detects stealthed enemies."
		}]
	},
	"Exo": {
		displayName: "Exo",
		built: ["Barracks"],
		faction: "v",
		subfaction: ["1v1", "Amara"],
		type: "Ground",
		building_requirement: ["Biokinetics Lab"],
		luminite: 100,
		therium: 25,
		supply: 2,
		buildtime: 28,
		speed: 4,
		size: 1.33,
		health: 130,
		armor_type: ["Biological", "Light"],
		armor: 0,
		veterancybonushealth: [26, 26, 26],
		veterancybonusdamage: ["10%", "10%","10%"],
		veterancyspecialbonus: ["0.5 Range", "0.5 Range", "0.5 Range" ],
		veterancyxp: [400, 1000, 1800],
		attacks: [{
			name: "BR-15 Rifle",
			target: ["Air", "Ground"],
			damage: 12,
			speed: 1,
			bonus: [ {bonus: 'Heavy', bonus_damage: 6 }],
			range: 7,
		}],
		traits: [{
			name: "Quickdraw Hustle",
			req: ["Research Quickdraw Hustle"],
			desc: "On-Attack: Gains 25% bonus movement speed for 2 seconds.",
		}, {
			name: "Survival Protocol",
			req: ["Research Survival Protocol"],
			desc: "This unit can negate fatal damage once every 120 seconds.",
		}],
	},
	"MedTech": {
		displayName: "MedTech",
		built: ["Barracks"],
		faction: "v",
		subfaction: ["1v1", "Amara"],
		type: "Ground",
		building_requirement: ["Central Command"],
		luminite: 100,
		therium: 50,
		supply: 3,
		buildtime: 30,
		speed:4,
		size: 1.8,
		health: 200,
		armor_type: ["Biological", "Heavy", "Mechanical"],
		armor: 5,
		energy: 25,
		max_energy: 100,
		energy_rate: 0.5,
		veterancybonushealth: [40, 40, 40],
		veterancybonusdamage: ["10%", "10%", "10%"],
		veterancyspecialbonus: ["0.25 Energy regeneration", "0.25 Energy regeneration", "0.25 Energy regeneration"],
		veterancyxp: [600, 1500, 2700],
		attacks: [{
			name: "Pulse Gauntlets",
			target: ["Air", "Ground"],
			damage: 5,
			speed: 2,
			range: 8.5,
		}],
		abilities: [{
			name: "Med Patch",
			energy: 5,
			casting_time: 0.5,
			cooldown: 2,
			duration: 2,
			desc: "Instantly heals a target biological units for 20 health and additional 20 health over 2 seconds. Grants it 25 bonus armor for the duration.",
		}, {
			name: "Nanoswarm",
			energy: 50,
			duration: 20,
			req: ["Research Medtech Adept Training"],
			desc: "Unleashes a swarm of nanobots onto a target unit. If the target is friendly, nearby mechanical units are healed for 20 health per second over 20 seconds. If the target is an enemy, nearby enemy mechanical units are damaged for 10 health per second. Right-click to enable autocasting. Automatically casts on damaged friendly mechanical units.",
		}, {
			name: "System Shock",
			energy: 50,
			req: ["Research Medtech Master Training"],
			desc: "Removes all positive buffs from enemy units in the target area. Removes all negative debuffs from friendly units in the area and grants them bonus movement speed",
		}],
	},
	"Hedgehog": {
		displayName: "Hedgehog",
		built: ["Mech Bay"],
		faction: "v",
		subfaction: ["1v1", "Blockade", "Amara"],
		type: "Ground",
		luminite: 150,
		therium: 25,
		supply: 3,
		buildtime: 30,
		speed: 6.75,
		size: 1.71,
		health: 230,
		armor_type: ["Light", "Mechanical"],
		armor: 5,
		veterancybonushealth: [46, 46, 46],
		veterancybonusdamage: ["10%", "10%", "10%"],
		veterancyspecialbonus: ["0.5 Range / 1 Range (Deployed)", "0.5 Range / 1 Range (Deployed)", "0.5 Range / 1 Range (Deployed)"],
		veterancyxp: [600, 1500, 2700],
		attacks: [{
			name: "UAM-22 Quill Rockets",
			target: ["Ground"],
			damage: 10,
			bonus: [ {bonus: "Heavy", bonus_damage: 5 }],
			speed: 0.3,
			range: 5
		}, {
			name: "UAM-22 Quill Rockets",
			target: ["Air"],
			damage: 10,
			speed: 0.3,
			range: 10,
		}],
		abilities: [{
			name: "Hunker Down",
			cooldown: 2,
			desc: "Deploy: Enables the Hedgehog's anti-air attack and decreases its ammo recharge time. Disables its anti-ground attack. Attacks Air",
		},{
			name: "Spine Up",
			cooldown: 2,
			desc: "Mobilize: Enables the Hedgehog's anti-ground attack and increases its ammo recharge time. Disables its anti-air attack. Attacks Ground",
		}],
		traits: [{
			name: "Transonic Boosters",
			req: ["Research Transonic Rockets"],
			desc: "+2/+4 weapon range.",
		},{
			name: "Vanguard Rocket Ammo",
			desc: "This unit uses ammo to attack and slowly recharges its ammo over time.",
		}],
		extra_info: [{
			name: "Ammo recharge",
			desc: "Mobilized ammo recharge time: 1 second, deployed: 0.5 seconds."
		}],
	},
	"Vulcan": {
		displayName: "Vulcan",
		built: ["Mech Bay"],
		faction: "v",
		subfaction: ["1v1", "Blockade"],
		type: "Ground",
		building_requirement: ["Central Command"],
		luminite: 200,
		therium: 125,
		supply: 5,
		buildtime: 45,
		speed: 3.5,
		size: 2.0,
		health: 450,
		armor_type: ["Heavy", "Mechanical"],
		armor: 10,
		veterancybonushealth: [90, 90, 90],
		veterancybonusdamage: ["10%", "10%", "10%"],
		veterancyspecialbonus: ["5% Attack Speed", "5% Attack Speed", "5% Attack Speed"],
		veterancyxp: [1000, 2500, 4500],
		attacks: [{
			name: "X134 Minigun",
			target: ["Ground"],
			damage: 3,
			speed: 0.25,
			bonus: [ {bonus: "Light", bonus_damage: 3 }],
			range: 8,
		}],
		abilities: [{
			name: "Jump Jets",
			cooldown: 15,
			duration: 3,
			range: 8,
			desc: "Launches this units towards a target location, stopping at and stunning the first enemy unit it impacts for 3 seconds. Destroy trees in its path."
		}],
		traits: [{
			name: "Vulcan Barrage",
			desc: "This unit's attacks deal area damage in a line and increase in power over time."
		}, {
			name: "Peak Performance",
			req: ["Research Peak Performance"],
			desc: "After using Jump Jets, this unit will deal max damage immediately."
		}],
		extra_info: [{
			name: "Attack winding up",
			desc: "Phase 1 damage: 3 (+3 vs Light), Phase 2 damage: 4 (+4 vs Light), Phase 3 damage: 6 (+6 vs Light). Loses windup after 1second of not attacking."
		}]
	},
	"Brute": {
		displayName: "Brute",
		built: ["Iron Vault"],
		faction: "i",
		subfaction: ["1v1"],
		type: "Ground",
		luminite: 100,
		therium: 0,
		supply: 2,
		buildtime: 0.5,
		charge_time: 35,
		speed: 4,
		size: 1.9,
		health: 160,
		extra_health: 40,
		armor_type: ["Biological", "Heavy"],
		armor: 5,
		attacks: [{
			name: "Fleshrender",
			target: ["Ground"],
			damage: 30,
			speed: 2.2,
			range: 0.5,
		}],
		abilities: [{
			name: "Sunder Soul",
			cooldown: 15,
			duration: 3,
			range: 8,
			desc: "Rips this unit in half, creating two Fiends in the process, granting them full White Health and 15% increased movement speed for 10 seconds. Passive: If a Brute dies naturally, it will produce two Fiends without White Health."
		}],
		traits: [{
			name: "Soulforge Ascendance",
			req: ["Research Soulforge Ascendance"],
			desc: "This unit will spawn an additional Fiend when it perishes, including when it uses Sunder Soul. Armor increased by 10."
		}, {
			name: "Sundering Soul Craze",
			req: ["Research Sundering Soul Craze"],
			desc: "Increases the attack speed of spawned Fiends by 50% for 10 seconds when this unit Sunders Soul."
		}]
	},
	"Magmadon": {
		displayName: "Magmadon",
		built: ["Iron Vault"],
		faction: "i",
		subfaction: ["1v1", "Warz"],
		type: "Ground",
		building_requirement: ["Greater Shrine"],
		luminite: 250,
		therium: 150,
		supply: 6,
		buildtime: 0.5,
		charge_time: 35,
		speed: 3.5,
		size: 2.57,
		health: 480,
		extra_health: 120,
		armor_type: ["Biological", "Heavy"],
		armor: 20,
		attacks: [{
			name: "Surge Smack",
			target: ["Ground"],
			damage: 30,
			speed: 2.1,
			range: 0.5,
		}],
		abilities: [{
			name: "Trample",
			cooldown: 16,
			duration: 6,
			desc: "Goes into a rampage, pushing nearby units out of the Magmadon's path and dealing 100 (+80 vs Heavy) damage over 6 seconds to nearby enemy ground units. Right-click to enable autocasting. Destroys trees.",
		}, {
			name: "Consume",
			casting_time: 0.4,
			cooldown: 5,
			desc: "Sacrifice a nearby Felhog or Fiend, recovering 100% of max White Health instantly.",
		}],
		traits: [{
			name: "Demonhoof Tremors",
			req: ["Research Demonhoof Tremors"],
			desc: "Allows Trample to periodically stun nearby enemy ground units.",
		}, {
			name: "Raging Tendons",
			req: ["Research Raging Tendons"],
			desc: "25% increased movement speed.",
		}],
	},
	"Hellborne": {
		displayName: "Hellborne",
		built: ["Iron Vault"],
		faction: "i",
		subfaction: ["1v1", "Maloc", "Warz"],
		type: "Ground",
		building_requirement: ["Greater Shrine"],
		luminite: 250,
		therium: 225,
		supply: 8,
		buildtime: 0.5,
		charge_time: 35,
		speed: 3.5,
		size: 2.71,
		health: 260,
		extra_health: 65,
		armor_type: ["Biological", "Heavy"],
		armor: 10,
		attacks: [{
			name: "Focused Hatred",
			target: ["Ground"],
			damage: 50,
			speed: 4,
			bonus: [ { bonus: "Structure", bonus_damage: 50 }],
			range: 14,
		}],
		traits: [{
			name: "Shatter",
			desc: "This unit's attack shatter on impact, dealing 25% of its primary damage to units behind the target.",
		}, {
			name: "Molten Touch",
			duration: 3,
			req: ["Research Molten Touch"],
			desc: "On-Hit: Lights target on fire, dealing 8 damage per second for 3 seconds.",
		}],
	},
	"Hexen": {
		displayName: "Hexen",
		built: ["Conclave"],
		faction: "i",
		subfaction: ["1v1", "Maloc", "Warz"],
		type: "Ground",
		building_requirement: ["Ritual Chamber"],
		luminite: 100,
		therium: 75,
		supply: 2,
		buildtime: 0.5,
		charge_time: 35,
		speed: 4,
		size: 1.7,
		health: 160,
		extra_health: 40,
		armor_type: ["Biological", "Light"],
		armor: 0,
		energy: 25,
		max_energy: 100,
		energy_rate: 0.5,
		attacks: [{
			name: "Scythe of Shedda",
			target: ["Air, Ground"],
			damage: 6,
			speed: 1.3,
			range: 7,
		}],
		abilities: [{
			name: "Skull of Shedda",
			energy: 25,
			cooldown: 5,
			desc: "Launches a cursed skull at a target enemy unit or location. The skull is controllable and can detonate on an enemy unit to Infest it and retain vision of nearby units for 10 seconds. Detector Right-click to enable autocasting.",
		}, {
			name: "Venom Trap",
			energy: 25,
			casting_time: 5,
			req: ["Research Hexen Adept Training"],
			desc: "Places an invisible trap on the ground. When an enemy ground unit walks over the trap, it explodes, dealing 50 damage to nearby enemy ground units, Infesting and revealing them.",
		}, {
			name: "Miasma",
			energy: 60,
			cooldown: 15,
			radius: 4,
			req: ["Research Hexen Master Training"],
			desc: "Covers a target area in bubbling ash and tar. Enemy ground units in the area will be Infested and take 700% bonus damage from Infest. This unit must channel this ability draining 4 energy per second.",
		}, {
			name: "Shroudweave",
			cooldown: 120,
			desc: "Teleports this unit to a friendly Command Structure, Shroudstone, or Wraithstone after a 3 second delay.",
		}],
		traits: [{
			name: "",
			desc: "",
		}],
	},
	"Weaver": {
		displayName: "Weaver",
		built: ["Conclave"],
		faction: "i",
		subfaction: ["1v1", "Maloc"],
		type: "Ground",
		building_requirement: ["Greater Shrine"],
		luminite: 100,
		therium: 150,
		supply: 4,
		buildtime: 0.5,
		charge_time: 35,
		speed: 2.5,
		size: 3.67,
		health: 580,
		extra_health: 145,
		armor_type: ["Biological", "Light"],
		armor: 0,
		energy: 50,
		max_energy: 100,
		energy_rate: 0.5,
		attacks: [{
			name: "Serrated Soul Knuckles",
			target: ["Ground"],
			damage_percentage: 15,
			speed: 2,
			range: 2,
			}, {
			name: "Serrated Soul Knuckles",
			target: ["Structure"],
			damage_percentage: 7.5,
			speed: 2,
			range: 2,
		}],
		abilities: [{
			name: "Lash",
			energy: 40,
			cooldown: 16,
			duration: 2,
			range: 10,
			desc: "Launches a harpoon at a target unit, pulling it to the location of the Weaver. If the target is an enemy, deals damage equal to 20% of its health and stuns it for 2 seconds. If the target is friendly, fully restores its White Health Right-click to enable/disable autocasting.",
		}, {
			name: "Consume",
			casting_time: 0.4,
			cooldown: 5,
			desc: "Sacrifice a nearby Felhog or Fiend, recovering 100% of max White Health instantly.",
		}, {
			name: "Shroudweave",
			cooldown: 120,
			desc: "Teleports this unit to a friendly Command Structure, Shroudstone, or Wraithstone after a 3 second delay.",
		}],
		traits: [{
			name: "High Sight",
			desc: "This unit can detect stealthed units and see onto high ground as if it were a flyer.",
		}, {
			name: "Soul Ripper",
			desc: "This unit's weapon deals 15% of the target unit's max health. 7.5% to structures.",
		}, {
			name: "Shroudwalk",
			desc: "This unit has 60% bonus movement speed in Shroud.",
		}],
	},
	"Imp": {
		displayName: "Imp",
		built: ["Shrine", "Greater Shrine", "Elder Shrine"],
		faction: "i",
		subfaction: ["1v1", "Maloc", "Warz"],
		type: "Ground",
		luminite: 50,
		supply: 1,
		buildtime: 0.5,
		charge_time: 17,
		speed: 3.5,
		size: 1.21,
		health: 80,
		extra_health: 20,
		armor_type: ["Biological", "Light"],
		armor: 0,
		attacks: [{
			name: "Ember",
			target: ["Ground"],
			damage: 6,
			speed: 1.5,
			range: 3,
		}],
		abilities: [{
			name: "Flame On",
			therium_cost: 25,
			casting_time: 1,
			duration: 4,
			req: ["Research Flame On"],
			desc: "Enflames this unit, increasing its movement speed and enabling it to explode into enemies at the cost of its health and shortening its lifespan to 4 seconds.",
		}],
	},
	"Kri": {
		displayName: "Kri",
		built: ["Creation Chamber"],
		faction: "c",
		subfaction: ["1v1", "Auralanna"],
		type: "Ground",
		building_requirement: ["Guardian Nexus"],
		luminite: 100,
		therium: 25,
		supply: 2,
		buildtime: 28,
		speed: 4.5,
		size: 1.29,
		health: 230,
		armor_type: ["Light", "Mechanical"],
		armor: 10,
		attacks: [{
			name: "Tetradedges",
			target: ["Ground"],
			damage: 14,
			speed: 1,
			bonus: [{ bonus: "Light", bonus_damage: 6 }],
			range: 0.1,
		}],
		traits: [{
			name: "Roll Out",
			req: ["Research Roll Out"],
			desc: "After not attacking for 3 seconds, this unit will tuck into a ball, gaining 30% bonus movement speed. The first attack in Ball Form will deal damage to all surrounding ground enemies.",
		}, {
			name: "Blaze of Light",
			damage: 20,
			desc: "When this unit takes fatal damage it will become invulnerable for 3 seconds and then explode, dealing 20 damage to nearby ground enemies.",
		}, {
			name: "Radiant Fury",
			damage: 20,
			req: ["Research Radiant Fury"],
			desc: "Improves Blaze of Light, increasing damage done by +20 and allowing Kri to move when they take fatal damage before they explode.",
		}],
	},
	"Scanner": {
		displayName: "Scanner",
		built: ["Creation Chamber"],
		faction: "c",
		subfaction: ["1v1", "Kastiel"],
		type: "Air",
		building_requirement: ["Arcstation"],
		luminite: 50,
		therium: 25,
		supply: 1,
		buildtime: 20,
		speed: 4.5,
		size: null,
		health: 70,
		armor_type: ["Light", "Mechanical"],
		armor: 0,
		energy: 25,
		max_energy: 100,
		energy_rate: 0.5,
		attacks: [{
			name: "Wota Tuul",
			target: ["Air", "Ground"],
			damage: 5,
			speed: 1,
			range: 3.5,
		}],
		abilities: [{
			name: "Perch",
			cooldown: 30,
			desc: "Situates iteself on top of a nearby tree, gaining Stealth and increased vision.",
		}, {
			name: "Tag",
			energy: 25,
			casting_time: 0.3,
			cooldown: 2,
			duration: 30,
			req: ["Research Tag"],
			desc: "Tags a nearby enemy unit, granting vision and detection around it for 30 seconds. Right-click to enable/disable autocasting.",
		}],
		traits: [{
			name: "Detector",
			desc: "Detects stealthed enemies.",
		}, {
			name: "Stealthed",
			desc: "Enemy players may only see this unit from afar if they have a Detector ability.",
		}],
	},
	"Cabal": {
		displayName: "Cabal",
		built: ["Creation Chamber"],
		faction: "c",
		subfaction: ["1v1", "Auralanna", "Kastiel"],
		type: "Ground",
		building_requirement: ["Arcstation"],
		luminite: 125,
		therium: 75,
		supply: 3,
		buildtime: 32,
		speed: 4,
		size: 1.8,
		health: 180,
		armor_type: ["Light", "Mechanical"],
		armor: 0,
		energy: 25,
		max_energy: 100,
		energy_rate: 0.5,
		attacks: [{
			name: "Canalizing Swarm",
			target: ["Air", "Ground"],
			damage: 2,
			speed: 0.25,
			range: 7,
		}],
		abilities: [{
			name: "Debilitate",
			energy: 35,
			duration: 25,
			range: 12,
			desc: "Reduces the target unit's damage and attack speed by 50% and movement speed by 25% for 25 seconds.",
		}, {
			name: "Gravity Flux",
			energy: 25,
			cooldown: 10,
			duration: 6,
			req: ["Research Cabal Adept Training"],
			desc: "Grounds an air unit or lifts a ground unit, stunning it for 6 seconds. Cannot target Resilient units. Right-click eneable autocasting. Automatically casts on enemy air units.",
		}, {
			name: "Mind Shackle",
			energy: 75,
			cooldown: 60,
			duration: 2,
			req: ["Research Cabal Master Training"],
			desc: "Links the Cabal with a target enemy ground unit. After 2 seconds, if the enemy unit is still within range, the Cabal will sacrifice itself to take permanent control of the target. Cannot target Resilient units.",
		}],
	},
	"Seraphim": {
		displayName: "Seraphim",
		built: ["Legion Hall"],
		faction: "c",
		subfaction: ["1v1", "Auralanna", "Kastiel"],
		type: "Air",
		luminite: 100,
		therium: 75,
		supply: 3,
		buildtime: 30,
		speed: 4.5,
		size: null,
		health: 180,
		armor_type: ["Biological", "Light"],
		armor: 0,
		energy: 50,
		max_energy: 100,
		energy_rate: 0.5,
		attacks: [{
			name: "Lawota of the Ventaora",
			target: ["Ground"],
			damage: 14,
			speed: 1,
			range: 6,
		}],
		abilities: [{
			name: "Condemnation",
			energy: 5,
			desc: "Increases the damage of this unit's attack against Creeps by 200%. Right-click to enable/disable autocasting.",
		}, {
			name: "Resolute Seal",
			energy: 50,
			casting_time: 0.5,
			req: ["Research Resolute Seal"],
			desc: "Disables all weapons, active abilities, and passive traits on a target enemy defensive structure for 30 seconds.",
		}, {
			name: "Winged Dash",
			cooldown: 15,
			duration: 2,
			desc: "Increases this unit's movement speed by 100% and allows it to evade 50% of incoming attacks for2 seconds. Right-click to enable/disable autocasting.",
		}],
		traits: [{
			name: "Creepbane Guard",
			desc: "This unit takes 50% damage reduction from Creeps.",
		}],
	},
	"Animancer": {
		displayName: "Animancer",
		built: ["Legion Hall"],
		faction: "c",
		subfaction: ["1v1", "Auralanna", "Kastiel"],
		type: "Ground",
		building_requirement: ["Ascension Matrix"],
		luminite: 100,
		therium: 150,
		supply: 4,
		buildtime: 40,
		speed: 3.5,
		size: 1.67,
		health: 220,
		armor_type: ["Biological", "Light"],
		armor: 0,
		energy: 25,
		max_energy: 100,
		energy_rate: 0.25,
		attacks: [{
			name: "Focus of the Empyrean",
			target: ["Air", "Ground"],
			damage: 15,
			speed: 2,
			range: 8,
		}],
		abilities: [{
			name: "Animus Redistribution",
			energy: 25,
			casting_time: 0.25,
			cooldown: 8,
			duration: 10,
			desc: "Drains 30 health and 15 energy per second from a target enemy unit over 10 seconds. 50% of the drained vitals are redistributed to friendly units near the Animancer. Right-click to enebale autocasting.",
		}, {
			name: "Unseen Veil",
			energy: 50,
			cooldown: 60,
			duration: 30,
			req: ["Research Animancer Adept Training"],
			desc: "Stealths nearby friendly units and structures for 30 seconds and increases their movement speed by 25%. Units unstealth upon attacking or being damaged.",
		}, {
			name: "Dark Prophecy",
			energy: 50,
			cooldown: 15,
			duration: 8,
			req: ["Research Animancer Master Training"],
			desc: "Triggers a singularity at a target location, slowing down all units in the area by 50%. Deals 20 damage per second to units in the area for 4 seconds and then 40 damage per second for an additional 4 seconds. Does not damage structures. The Animancer must channel the singularity.",
		}],
	},
	"Archangel": {
		displayName: "Archangel",
		built: ["Legion Hall"],
		faction: "c",
		subfaction: ["1v1", "Auralanna", "Kastiel"],
		type: "Ground",
		building_requirement: ["Arcfortress"],
		luminite: 400,
		therium: 300,
		supply: 12,
		buildtime: 65,
		speed: 5.5,
		size: 2.83,
		health: 750,
		armor_type: ["Biological", "Heavy"],
		armor: 20,
		energy: 50,
		max_energy: 100,
		energy_rate: 0.25,
		attacks: [{
			name: "Maza's Might",
			target: ["Air"],
			damage: 120,
			speed: 2,
			range: 0.1,
		}, {
			name: "Maza's Might",
			target: ["Ground"],
			damage: 120,
			speed: 2,
			range: 0.1,
		}],
		abilities: [{
			name: "Angelic Descent",
			desc: "The Archangel lands back on earth, allowing it to attack ground units and use the Avatar ability.",
		}, {
			name: "Angelic Ascent",
			desc: "The Archangel launches into the skies, allowing it to attack air units and use the Meteor Strike ability.",
		}, {
			name: "Meteor Strike",
			energy: 50,
			casting_time: 0.133,
			desc: "Divebomb a target location, quickly descending, dealing 100 area damage to nearby enemy ground units on impact.",
		}, {
			name: "Avatar",
			energy: 50,
			cooldown: 120,
			desc: "The Archangel charges its body with pure Celestial energy, increasing its health by 400 and gaining resilience to enemy disables. Its attacks become ranged and deals damage in a line. Lasts 20 seconds.",
		}],
		traits: [{
			name: "Scorched Earth",
			duration: 10,
			req: ["Research Scorched Earth"],
			desc: "Allows Meteor Strike to set the ground on fire on impact, dealing 20 damage per second to enemy ground units over 10 seconds.",
		}],
	},
	"Saber": {
		displayName: "Saber",
		built: ["Starforge"],
		faction: "c",
		subfaction: ["1v1", "Auralanna", "Kastiel"],
		type: "Ground",
		building_requirement: ["Arcstation"],
		luminite: 225,
		therium: 125,
		supply: 6,
		buildtime: 45,
		speed: 3,
		size: 2.57,
		health: 250,
		armor_type: ["Heavy", "Mechanical"],
		armor: 10,
		attacks: [{
			name: "Dark Matter Cannon",
			target: ["Ground"],
			damage: 60,
			speed: 2.5,
			bonus: [{ bonus: "Heavy", bonus_damage: 30 }],
			range: 14,
		}],
		abilities: [{
			name: "Mass Accelerator",
			cooldown: 20,
			duration: 5,
			desc: "Increases the movement speed of this unit by 100% for 5 seconds. If the Saber attacks while accelerated, its engines will cool and it will revert back to its base speed.",
		}, {
			name: "Self-Repair",
			cooldown: 20,
			desc: "Channels this unit's core to fully restore its health. The Saber cannot attack or move while self-repairing and will cease repairs if given another order.",
		}],
		traits: [{
			name: "Dark Matter Distortion",
			desc: "This unit's attack deals 50% of its damage to adjacent enemies.",
		}, {
			name: "Core Ascendancy",
			req: ["Research Core Ascendancy"],
			desc: "Increases the duration of Mass Accelerator's speed bonus from 5 seconds to 10 seconds. Increases the heal rate of Self-Repair from 10 health to 30 health per second.",
		}],
	},
	"Vector": {
		displayName: "Vector",
		built: ["Starforge"],
		faction: "c",
		subfaction: ["1v1", "Auralanna", "Kastiel"],
		type: "Ground",
		luminite: 150,
		therium: 50,
		supply: 3,
		buildtime: 32,
		speed: 5,
		size: 1.67,
		health: 195,
		armor_type: ["Light", "Mechanical"],
		armor: 0,
		attacks: [{
			name: "Cartesian Cannonade",
			target: ["Air"],
			damage: 6,
			speed: 1.3,
			bonus: [{ bonus: "Light", bonus_damage: 6 }],
			range: 6,
		}, {
			name: "Cartesian Cannonade",
			target: ["Ground"],
			damage: 6,
			speed: 1.3,
			bonus: [{ bonus: "Light", bonus_damage: 6 }],
			range: 3,
		}],
		abilities: [{
			name: "Delta Jump",
			cooldown: 15,
			desc: "Teleports to a nearby target location, turning into a Temporal form. While Temporal the Vector will take 50% bonus damage from attacks and has the ability to Recall to its original location.",
		}, {
			name: "Recall",
			req: ["Research Recall"],
			desc: "Returns the Vector to its previous location, restoring it's original health.",
		}],
		traits: [{
			name: "Trichotomic Barrage",
			desc: "This unit fires three missles with each attack.",
		}, {
			name: "Recall Potential",
			req: ["Research Recall"],
			desc: "30% incrased movement speed and allows this unit to Recall after Delta Jumping, returning them to their previous location with their original health.",
		}],
	},
	"Graven": {
		displayName: "Graven",
		built: ["Barracks"],
		faction: "v",
		subfaction: ["1v1", "Blockade", "Amara"],
		type: "Ground",
		building_requirement: ["High Command"],
		luminite: 125,
		therium: 75,
		supply: 4,
		buildtime: 38,
		speed: 4,
		size: 1.22,
		health: 220,
		armor_type: ["Biological", "Light"],
		energy: 25,
		max_energy: 100,
		energy_rate: 0.5,
		veterancybonushealth: [44, 44, 44],
		veterancybonusdamage: ["10%", "10%", "10%"],
		veterancyspecialbonus: ["10% Movement Speed", "10% Movement Speed", "10% Movement Speed"],
		veterancyxp: [800, 2000, 3600],
		attacks: [{
			name: "Ku-9s",
			target: ["Air", "Ground"],
			damage: 10,
			speed: 0.7,
			bonus: [{ bonus: "Light", bonus_damage: 15 }],
			range: 6,
		}],
		abilities: [{
			name: "Phase Shift",
			cooldown: 10,
			desc: "Teleports to a nearby target location and Stealths.",
		}, {
			name: "Sticky Bomb",
			energy: 40,
			cooldown: 20,
			desc: "Throws a bomb at a target ground unit or location. After 3 seconds, it will explode, dealing 50 damage to and leaving behind goop that slows all ground units in an area.",
		}, {
			name: "Infiltrate",
			energy: 40,
			casting_time: 5,
			desc: "Targets an enemy structure. After channeling for 5 seconds, the structure will be dealt 500 damage, disabled for 20 seconds, and revealed. 50 Luminite and 50 Therium will be stolen from the player, and the player's Top-Bar will be disabled if is a Command Structure.",
		}],
		traits: [{
			name: "Adaptive Camouflage",
			desc: "Enters Stealth when out of combat for 3 seconds.",
		}, {
			name: "Mass Infiltration",
			req: ["Research Mass Infiltrate"],
			desc: "Allows Infiltrate to disable multiple structures in a moderate area around the target structure.",
		}],
	},
			
	/*
	"": {
		displayName: "",
		attacks: [{
			target: "",
			damage: ,
			speed: ,
			bonus: [ { bonus: "", bonus_damage:  }],
			range: ,
		}],
		abilities: [{
			name: "",
			energy: ,
			desc: "",
		}],
		traits: [{
			name: "",
			desc: "",
		}],
	}
	*/
};
