const gUnits = {
	"Argent": {
		name: "Argent",
		built: ["Creation Chamber"],
		faction: "c",
		type: "Ground",
		luminite: 100,
		therium: 0,
		supply: 2,
		buildtime: 26,
		speed: 4.5,
		health: 180,
		armor_type: ['Biological', 'Heavy', 'Mechanical'],
		armor: 5,
		energy: 30,
		attacks: [{
			name: 'Oscillamata',
			target: ['Air', 'Ground'],
			damage: 8,
			speed: 1.5,
			bonus: [ { bonus: 'Heavy', bonus_damage: 4 }],
			range: 6,
		}],
		abilities: [{
			name: 'High Energy',
			energy: 10,
			desc: "Imbues this unit's weapon, allowing it to deal 100% increased damage. Right-click to enable/disable autocasting.",
		}],
		traits: [{
			name: 'Photo-Restoration',
			desc: "When this unit is out of combat, it regenerates 2 energy per second.",
		}, {
			name: 'Longshot Module',
			req: ['Research Photo-Capacitors', 'Research Longshot Module'],
			desc: "Increases the range of this unit's charged weapon by +3.",
		}, {
			name: 'Photo-Capacitors',
			req: ['Research Photo-Capacitors'],
			desc: "+20 starting and maximum energy.",
		}],
	},
	"Gaunt": {
		name: "Gaunt",
		built: ["Conclave"],
		faction: "i",
		type: "Ground",
		luminite: 50,
		therium: 12.5,
		supply: 1,
		buildtime: 0.5,
		charge_time: 35,
		speed: 4,
		health: 80,
		extra_health: 20,
		armor_type: ['Biological', 'Light'],
		armor: 0,
		energy: 0,
		attacks: [{
			name: 'Flying Bone Axes',
			target: ['Air'],
			damage: 8,
			speed: 1.3,
			bonus: [ { bonus: 'Light', bonus_damage: 4 }],
			range: 6,
		}, {
			name: 'Bone Axes',
			target: ['Ground'],
			damage: 8,
			speed: 1.3,
			bonus: [ { bonus: 'Light', bonus_damage: 4 }],
			range: 5,
		}],
		extra_info: [{
			name: 'Spawns in pair',
			desc: "Charge makes 2 gaunts",
		}, {
			name: 'Bounces',
			desc: "Attacks bounce to two nearby targets, dealing 2 (+1 vs Light) damage.",
		}],
		abilities: [],
		traits: [{
			name: "Bouncing Bone Axes",
			range: 3.5,
			desc: "On-Hit: Attacks bounce twice to nearby enemies, dealing 25% of primary damage.",
		}, {
			name: 'Plague Axe',
			req: ['Research Plague Axe'],
			desc: "On-Hit: Attacked units within Shroud are infected with Infest.",
		}, {
			name: "Reaper's Rush",
			req: ["Research Reaper's Rush"],
			desc: "30% increased movement speed.",
		}],
	},
	"Atlas": {
		name: 'Atlas',
		built: ['Mech Bay'],
		faction: 'v',
		subfaction: ['1v1', 'Blockade', 'Amara'],
		type: 'Ground',
		building_requirement: ['Machine Lab'],
		luminite: 250,
		therium: 125,
		supply: 6,
		buildtime:48,
		speed:3,
		health:300,
		armor_type: ['Heavy', 'Mechanical'],
		armor:10,
		veterancybonushealth: [60, 60, 60],
		veterancybonusdamage: ['10%', '10%', '10%'],
		veterancyspecialbonus: ['1 (Deployed) Range', '1 (Deployed) Range', '1 (Deployed) Range'],
		veterancyxp: [1200, 3000, 5400],
		attacks: [{
			name: 'L.I.G.H.T. Guns',
			target: ['Ground'],
			damage: 15,
			speed: 0.5,
			range: 4,
		}, {
			name: 'BFG',
			target: ['Ground'],
			damage: 80,
			speed: 5,
			bonus: [ { bonus: 'Heavy', bonus_damage: 35 }, { bonus: 'Structure', bonus_damage: 35 }],
			range: 16,
		}],
		abilities: [{
			name: 'Deploy BFG',
			cooldown: 1.5,
			desc: "Deploy: Greatly increases the range of the Atlas' attack. Attacks Ground",
		}, {
			name: 'Pack It Up',
			cooldown: 1.167,
			desc: "Mobilize: Greatly reduce the range of the Atlas' attack. Attacks Ground",
		}],
		traits: [{
			name: 'Purification Ordnance',
			req: ['Deploy BFG'],
			desc: "This unit's attacks deal area damage in a circle.",
		}, {
			name: 'Plasma Arc Infusion',
			duration: 5,
			req: ['Research Plasma Arc Infusion'],
			desc: "On-Hit: Lights the ground on fire, dealing 20 damage per second to all units standing in the fire for 5 seconds.",
		}],
	},
	"BOB": {
		name: 'B.O.B.',
		built: ['Command Post', 'Central Command', 'High Command'],
		faction: 'v',
		subfaction: ['1v1', 'Blockade', 'Amara'],
		type: 'Ground',
		luminite: 50,
		therium: 0,
		supply: 1,
		buildtime: 17,
		speed: 3.5,
		health: 130,
		armor_type: ['Light', 'Mechanical'],
		armor: 0,
		veterancybonushealth: [26, 26, 26],
		veterancybonusdamage: ['10%', '10%', '10%'],
		veterancyspecialbonus: ['20% Construction Speed', '20% Construction Speed', '20% Construction Speed'],
		veterancyxp: [200, 500, 900],
		attacks: [{
			name: 'Servo-Fists',
			target: ['Ground'],
			damage: 8,
			speed: 1.5,
			range: 0.1,
		}],
		abilities: [{
			name: 'Repair',
			desc: "Restores health to mechanical units and structures.",
		}],
	},
	"Lancer": {
		name: 'Lancer',
		built: ['Barracks'],
		faction: 'v',
		subfaction: ['1v1'],
		type: 'Ground',
		luminite: 100,
		therium: 0,
		supply: 2,
		buildtime: 24,
		speed: 4.5,
		health: 260,
		armor_type: ['Biological', 'Heavy'],
		armor: 15,
		veterancybonushealth: [48, 48, 48],
		veterancybonusdamage: ['10%', '10%', '10%'],
		veterancyspecialbonus: ['5 Armor', '5 Armor', '5 Armor'],
		veterancyxp: [400, 1000, 1800],
		attacks: [{
			name: 'Foe Splitter Blade',
			target: ['Ground'],
			damage: 10,
			speed: 1.5,
			bonus: [ {bonus: 'Structure', bonus_damage:5 }, {bonus: 'Light', bonus_damage:5 }],
			range: 1.5,
		}],
		traits: [{
			name: 'Vanguard Fortified Impaler',
			desc: "This units attacks deal area damage in a line.",
		},{
			name: 'Vanguard Kinetic Redirection',
			duration: 5,
			req: ['Research Kinetic Redirection'],
			desc: "On-Damaged: Increases this unit's attack and movement speed by 5% for 5 seconds. Max 50%.",
		},{
			name: 'Vanguard Mitigative Guard',
			req: ['Research Mitigative Guard'],
			desc: "On-Damaged: Damage reduced by 2.",
		}],
	},
	"SCOUT": {
		name: "S.C.O.U.T.",
		built: ["Barracks"],
		faction: "v",
		subfaction: ["1v1", "Amara"],
		type: "Ground",
		luminite: 50,
		therium: 0,
		supply: 1,
		buildtime: 18,
		speed: 7,
		health: 120,
		armor_type: ["Biological", "Light", "Mechanical"],
		armor: 0,
		veterancybonushealth: [24, 24, 24],
		veterancybonusdamage: ["10%", "10%", "10%"],
		veterancyspecialbonus: ["2 Vision", "2 Vision", "2 Vision"],
		veterancyxp: [200, 400, 900],
		attacks: [{
			name: "Metallic Cruncher",
			target: ["Ground"],
			damage: 5,
			speed: 1.4,
			bonus: [ {bonus: 'Light', bonus_damage: 3 }],
			range: 0.1
		}],
		abilities: [{
					name: "On The Hunt",
					cooldown: 40,
					duration: 10,
					desc: "Greatly increases the S.C.O.U.T.'s vision radius for 10 seconds."
				},{
					name: "Pounce",
					cooldown: 30,
					req: ["Research Pounce"],
					desc: "Intercepts a nearby enemy unit, increasing this unit's movement speed by 25% and dealing 15 (+15 vs Light) bonus damage on impact."
		}],
		traits: [{
			name: "Pupper Sense",
			desc: "This unit can sense nearby enemies under the fog of war."
		},{
			name: "Vorillium Claws",
			req: ["Research Vorillium Claws"],
			desc: "Increased damage against Light units by +8."
		},{
			name: "Detector",
			desc: "Detects stealthed enemies."
		}]
	},
	"Exo": {
		name: "Exo",
		built: ["Barracks"],
		faction: "v",
		subfaction: ["1v1", "Amara"],
		type: "Ground",
		building_requirement: ["Biokinetics Lab"],
		luminite: 100,
		therium: 25,
		supply: 2,
		buildtime: 28,
		speed: 4,
		health: 130,
		armor_type: ["Biological", "Light"],
		armor: 0,
		veterancybonushealth: [26, 26, 26],
		veterancybonusdamage: ["10%", "10%","10%"],
		veterancyspecialbonus: ["0.5 Range", "0.5 Range", "0.5 Range" ],
		veterancyxp: [400, 1000, 1800],
		attacks: [{
			name: "BR-15 Rifle",
			target: ["Air", "Ground"],
			damage: 12,
			speed: 1,
			bonus: [ {bonus: 'Heavy', bonus_damage: 6 }],
			range: 7,
		}],
		traits: [{
			name: "Quickdraw Hustle",
			req: ["Research Quickdraw Hustle"],
			desc: "On-Attack: Gains 25% bonus movement speed for 2 seconds.",
		}, {
			name: "Survival Protocol",
			req: ["Research Survival Protocol"],
			desc: "This unit can negate fatal damage once every 120 seconds.",
		}],
	},
	"MedTech": {
		name: "MedTech",
		built: ["Barracks"],
		faction: "v",
		subfaction: ["1v1", "Amara"],
		type: "Ground",
		building_requirement: ["Central Command"],
		luminite: 100,
		therium: 50,
		supply: 3,
		buildtime: 30,
		speed:4,
		health: 200,
		armor_type: ["Biological", "Heavy", "Mechanical"],
		armor: 5,
		energy: 25,
		max_energy: 100,
		energy_rate: 0.5,
		veterancybonushealth: [40, 40, 40],
		veterancybonusdamage: ["10%", "10%", "10%"],
		veterancyspecialbonus: ["0.25 Energy regeneration", "0.25 Energy regeneration", "0.25 Energy regeneration"],
		veterancyxp: [600, 1500, 2700],
		attacks: [{
			name: "Pulse Gauntlets",
			target: ["Air", "Ground"],
			damage: 5,
			speed: 2,
			range: 8.5,
		}],
		abilities: [{
			name: "Med Patch",
			energy: 5,
			casting_time: 0.5,
			cooldown: 2,
			duration: 2,
			desc: "Instantly heals a target biological units for 20 health and additional 20 health over 2 seconds. Grants it 25 bonus armor for the duration.",
		}, {
			name: "Nanoswarm",
			energy: 50,
			duration: 20,
			req: ["Research Medtech Adept Training"],
			desc: "Unleashes a swarm of nanobots onto a target unit. If the target is friendly, nearby mechanical units are healed for 20 health per second over 20 seconds. If the target is an enemy, nearby enemy mechanical units are damaged for 10 health per second. Right-click to enable autocasting. Automatically casts on damaged friendly mechanical units.",
		}, {
			name: "System Shock",
			energy: 50,
			req: ["Research Medtech Master Training"],
			desc: "Removes all positive buffs from enemy units in the target area. Removes all negative debuffs from friendly units in the area and grants them bonus movement speed",
		}],
	},
	"Hedgehog": {
		name: "Hedgehog",
		built: ["Mech Bay"],
		faction: "v",
		subfaction: ["1v1", "Blockade", "Amara"],
		type: "Ground",
		luminite: 150,
		therium: 25,
		supply: 3,
		buildtime: 30,
		speed: 6.75,
		health: 230,
		armor_type: ["Light", "Mechanical"],
		armor: 5,
		veterancybonushealth: [46, 46, 46],
		veterancybonusdamage: ["10%", "10%", "10%"],
		veterancyspecialbonus: ["0.5 Range / 1 Range (Deployed)", "0.5 Range / 1 Range (Deployed)", "0.5 Range / 1 Range (Deployed)"],
		veterancyxp: [600, 1500, 2700],
		attacks: [{
			name: "UAM-22 Quill Rockets",
			target: ["Ground"],
			damage: 10,
			bonus: [ {bonus: "Heavy", bonus_damage: 5 }],
			speed: 0.3,
			range: 5
		}, {
			name: "UAM-22 Quill Rockets",
			target: ["Air"],
			damage: 10,
			speed: 0.3,
			range: 10,
		}],
		abilities: [{
			name: "Hunker Down",
			cooldown: 2,
			desc: "Deploy: Enables the Hedgehog's anti-air attack and decreases its ammo recharge time. Disables its anti-ground attack. Attacks Air",
		},{
			name: "Spine Up",
			cooldown: 2,
			desc: "Mobilize: Enables the Hedgehog's anti-ground attack and increases its ammo recharge time. Disables its anti-air attack. Attacks Ground",
		}],
		traits: [{
			name: "Transonic Boosters",
			req: ["Research Transonic Rockets"],
			desc: "+2/+4 weapon range.",
		},{
			name: "Vanguard Rocket Ammo",
			desc: "This unit uses ammo to attack and slowly recharges its ammo over time.",
		}],
		extra_info: [{
			name: "Ammo recharge",
			desc: "Mobilized ammo recharge time: 1 second, deployed: 0.5 seconds."
		}],
	},
	"Vulcan": {
		name: "Vulcan",
		built: ["Mech Bay"],
		faction: "v",
		subfaction: ["1v1", "Blockade"],
		type: "Ground",
		building_requirement: ["Central Command"],
		luminite: 200,
		therium: 125,
		supply: 5,
		buildtime: 45,
		speed: 3.5,
		health: 450,
		armor_type: ["Heavy", "Mechanical"],
		armor: 10,
		veterancybonushealth: [90, 90, 90],
		veterancybonusdamage: ["10%", "10%", "10%"],
		veterancyspecialbonus: ["5% Attack Speed", "5% Attack Speed", "5% Attack Speed"],
		veterancyxp: [1000, 2500, 4500],
		attacks: [{
			name: "X134 Minigun",
			target: ["Ground"],
			damage: 3,
			speed: 0.25,
			bonus: [ {bonus: "Light", bonus_damage: 3 }],
			range: 8,
		}],
		abilities: [{
			name: "Jump Jets",
			cooldown: 15,
			duration: 3,
			range: 8,
			desc: "Launches this units towards a target location, stopping at and stunning the first enemy unit it impacts for 3 seconds. Destroy trees in its path."
		}],
		traits: [{
			name: "Vulcan Barrage",
			desc: "This unit's attacks deal area damage in a line and increase in power over time."
		}, {
			name: "Peak Performance",
			req: ["Research Peak Performance"],
			desc: "After using Jump Jets, this unit will deal max damage immediately."
		}],
		extra_info: [{
			name: "Attack winding up",
			desc: "Phase 1 damage: 3 (+3 vs Light), Phase 2 damage: 4 (+4 vs Light), Phase 3 damage: 6 (+6 vs Light). Loses windup after 1second of not attacking."
		}]
	},
	/*
	"": {
		attacks: [{
			target: "",
			damage: ,
			speed: ,
			bonus: [ { bonus: "", bonus_damage:  }],
			range: ,
		}],
		abilities: [{
			name: "",
			energy: ,
			desc: "",
		}],
		traits: [{
			name: "",
			desc: "",
		}],
	}
	*/
};
